# Note: this is intended for LOCAL TESTING ONLY.
#
# Does not require any special Docker networks or other configuration.
# Services that connect to it should attempt to connect to the desired
# port on localhost.

version: '2'

services:
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181            # Zookeeper
      - 3030:3030            # Landoop UI
      - 8081-8083:8081-8083  # REST Proxy, Schema Registry, Kafka Connect
      - 9581-9585:9581-9585  # JMX Ports
      - 9092:9092            # Kafka Broker